### ISSUE TITLE
Is 2 ALB needed?

### ISSUE THREAD

**Issue by Irek-h** [itz-mathesh/aws-public-private-subnet-architecture#1]
Hi!

I have a question regarding the necessity of 2 LB on the diagram? Correct me if I'm wrong, but Load Balancers are out of the box highly available, and we only need one to serve the traffic across many AZs. I'm preparing for the SAA and wanted to make sure I'm not mistaken. Great medium post btw, gonna dig into it

**Comment by mathesh-me** [comment]
Hi @Irek-h, Thanks for bringing up the issue. It will be helpful for others who have the same doubt.

Your question is valid. Apologies for any inconvenience caused by the diagram. It's important to clarify that the diagram **doesn't mean the deployment of ALB in two Availability Zones (AZs)**. The box with hyphens represents two ALBs, indicating that we intend to point our ALB to instances in two AZs, rather than deploying it directly in two AZs. ALBs are not created at the AZ level. 
AWS has provided official documentation on Private Public Subnet Architecture, which you can refer to for further information: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-example-private-subnets-nat.html

**Comment by mathesh-me** [comment]
Hi @Irek-h, Thanks for bringing up the issue. It will be helpful for others who have the same doubt.

Your question is valid. Apologies for any inconvenience caused by the diagram. It's important to clarify that the diagram **doesn't mean the deployment of ALB in two Availability Zones (AZs)**. The box with hyphens represents two ALBs, indicating that we intend to point our ALB to instances in two AZs, rather than deploying it directly in two AZs. ALBs are not created at the AZ level. 
AWS has provided official documentation on Private Public Subnet Architecture, which you can refer to for further information: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-example-private-subnets-nat.html

**Comment by mathesh-me** [comment]
Hi @Irek-h, Thanks for bringing up the issue. It will be helpful for others who have the same doubt.

Your question is valid. Apologies for any inconvenience caused by the diagram. It's important to clarify that the diagram **doesn't mean the deployment of ALB in two Availability Zones (AZs)**. The box with hyphens represents two ALBs, indicating that we intend to point our ALB to instances in two AZs, rather than deploying it directly in two AZs. ALBs are not created at the AZ level. 
AWS has provided official documentation on Private Public Subnet Architecture, which you can refer to for further information: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-example-private-subnets-nat.html
